server:
  port: 8888

spring:
  application:
    name: Config-Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/revaturelabs/scrumboard-config-files.git
          default-label: localTestBranch
          
