server:
  port: 8888

spring:
  application:
    name: Config-Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rbunning/JABR-Project-3-config-yml-files.git
          default-label: localTestBranch
          
